name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get the webapp
      run: git clone --depth 1 https://github.com/Miouyouyou/mattermost-webapp && mv mattermost-webapp ../
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Package
      run: ls -l && make package
